In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [38]:
df = pd.read_csv('Churn_Modelling.csv ')

In [39]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

***DROPPING COLUMNS***

In [40]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [41]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

***SPLITTING INTO X AND y***

In [42]:
X = df.drop('Exited', axis = 1) # features
y = df['Exited'] # Target

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
# Encoding

from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [46]:
encoder = OneHotEncoder(sparse_output= False)

In [47]:
numerical_features = df.select_dtypes(include= [np.number]).columns.tolist()
categorical_features = df.select_dtypes(exclude= [np.number]).columns.tolist()

In [48]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Create some sample categorical data
X_categorical = np.array([['Male', 'New York'], 
                          ['Female', 'California'], 
                          ['Female', 'New York'], 
                          ['Male', 'California']])

# Create and apply the encoder
encoder = OneHotEncoder(sparse_output=False)
encoded_array = encoder.fit_transform(X_categorical)

# Display the result
print("Original categorical data:")
print(X_categorical)
print("\nOne-hot encoded numpy array:")
print(encoded_array)
print("\nFeature names:")
print(encoder.get_feature_names_out())

Original categorical data:
[['Male' 'New York']
 ['Female' 'California']
 ['Female' 'New York']
 ['Male' 'California']]

One-hot encoded numpy array:
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]

Feature names:
['x0_Female' 'x0_Male' 'x1_California' 'x1_New York']


In [49]:
encoded_geo_value_train = encoder.fit_transform(X_train[categorical_features])
encoded_geo_value_test = encoder.transform(X_test[categorical_features])

In [50]:
encoded_names = encoder.get_feature_names_out()

In [51]:
merged_train = pd.DataFrame(
    encoded_geo_value_train,
    columns= encoded_names
)

In [52]:
merged_test = pd.DataFrame(
    encoded_geo_value_test,
    columns= encoded_names
)

In [53]:
merged_test

Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                  0.0                1.0              0.0            0.0   
1                  1.0                0.0              0.0            0.0   
2                  0.0                0.0              1.0            1.0   
3                  0.0                1.0              0.0            0.0   
4                  0.0                0.0              1.0            1.0   
...                ...                ...              ...            ...   
1995               0.0                1.0              0.0            1.0   
1996               1.0                0.0              0.0            0.0   
1997               1.0                0.0              0.0            1.0   
1998               1.0                0.0              0.0            0.0   
1999               0.0                1.0              0.0            0.0   

      Gender_Male  
0             1.0  
1             1.0  
2             0.0  
3             1.0  
4             0.0  
...           ...  
1995          0.0  
1996          1.0  
1997          0.0  
1998          1.0  
1999          1.0  

[2000 rows x 5 columns]

In [54]:
X_train.reset_index(drop= True, inplace= True)
X_test.reset_index(drop= True, inplace= True)

In [55]:
X_train = pd.concat([X_train, merged_train],axis=1)

In [56]:
X_test = pd.concat([X_test, merged_test],axis=1)

In [57]:
X_test.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          596   Germany    Male   32       3   96709.07              2   
1          623    France    Male   43       1       0.00              2   
2          601     Spain  Female   44       4       0.00              2   
3          506   Germany    Male   59       8  119152.10              2   
4          560     Spain  Female   27       7  124995.98              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Geography_France  \
0          0               0         41788.37               0.0   
1          1               1        146379.30               1.0   
2          1               0         58561.31               0.0   
3          1               1        170679.74               0.0   
4          1               1        114669.79               0.0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                1.0              0.0            0.0          1.0  
1                0.0              0.0            0.0          1.0  
2                0.0              1.0            1.0          0.0  
3                1.0              0.0            0.0          1.0  
4                0.0              1.0            1.0          0.0

***SCALING NUMERIC FEATURES***

In [58]:
numerical_features.pop()

'Exited'

In [59]:
Scaler = StandardScaler()
X_train[numerical_features] = Scaler.fit_transform(X_train[numerical_features])

In [60]:
X_test[numerical_features] =Scaler.transform(X_test[numerical_features])

In [61]:
X_train

CreditScore Geography  Gender       Age    Tenure   Balance  \
0        0.356500    France    Male -0.655786  0.345680 -1.218471   
1       -0.203898   Germany    Male  0.294938 -0.348369  0.696838   
2       -0.961472     Spain    Male -1.416365 -0.695393  0.618629   
3       -0.940717    France  Female -1.131148  1.386753  0.953212   
4       -1.397337    France    Male  1.625953  1.386753  1.057449   
...           ...       ...     ...       ...       ...       ...   
7995     1.207474    France    Male  1.435808  1.039728 -0.102301   
7996     0.314989    France  Female  1.816097 -1.389442 -1.218471   
7997     0.865009    France  Female -0.085351 -1.389442 -1.218471   
7998     0.159323    France    Male  0.390011  1.039728  1.827259   
7999     0.470655   Germany    Male  1.150590 -1.389442  1.149720   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.808436   0.649203        0.974817         1.367670   
1          0.808436   0.649203        0.974817         1.661254   
2         -0.916688   0.649203       -1.025834        -0.252807   
3         -0.916688   0.649203       -1.025834         0.915393   
4         -0.916688  -1.540351       -1.025834        -1.059600   
...             ...        ...             ...              ...   
7995      -0.916688   0.649203        0.974817        -0.539860   
7996      -0.916688   0.649203        0.974817        -1.733882   
7997       2.533560  -1.540351       -1.025834        -0.142765   
7998      -0.916688   0.649203       -1.025834        -0.050826   
7999      -0.916688   0.649203        0.974817        -0.814568   

      Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                  1.0                0.0              0.0            0.0   
1                  0.0                1.0              0.0            0.0   
2                  0.0                0.0              1.0            0.0   
3                  1.0                0.0              0.0            1.0   
4                  1.0                0.0              0.0            0.0   
...                ...                ...              ...            ...   
7995               1.0                0.0              0.0            0.0   
7996               1.0                0.0              0.0            1.0   
7997               1.0                0.0              0.0            1.0   
7998               1.0                0.0              0.0            0.0   
7999               0.0                1.0              0.0            0.0   

      Gender_Male  
0             1.0  
1             1.0  
2             1.0  
3             0.0  
4             1.0  
...           ...  
7995          1.0  
7996          0.0  
7997          0.0  
7998          1.0  
7999          1.0  

[8000 rows x 15 columns]

In [62]:
X_train.drop(categorical_features, axis=1, inplace=True)
X_test.drop(categorical_features, axis=1, inplace=True)

***MODEL BUILDING AND EVALUATION***

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

In [64]:
model_dict = {
    'lr' : LogisticRegression(max_iter=1000, random_state = 42),
    'dt' : DecisionTreeClassifier(random_state=42),
    'rf' :RandomForestClassifier(random_state=42)
}

In [65]:
accuracy_per_model = {}

In [66]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [67]:
for name, model in model_dict.items():
    models = model
    models.fit(X_train, y_train)
    print(f"\n.........{name}........\n")
    y_pred = models.predict(X_test)
    print(f"Accuracy for {name}")
    print(accuracy_score(y_test, y_pred))
    print("\n.......................\n")
    print(f"Confusion matrix for {name}")
    print(confusion_matrix(y_test, y_pred))
    print("\n.......................\n")
    print(f"Classification report for {name}")
    print(classification_report(y_test, y_pred))

    accuracy_per_model[f'accuracy_{name}_model'] = accuracy_score(y_test, y_pred)


.........lr........

Accuracy for lr
0.811

.......................

Confusion matrix for lr
[[1543   64]
 [ 314   79]]

.......................

Classification report for lr
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000


.........dt........

Accuracy for dt
0.7805

.......................

Confusion matrix for dt
[[1362  245]
 [ 194  199]]

.......................

Classification report for dt
              precision    recall  f1-score   support

           0       0.88      0.85      0.86      1607
           1       0.45      0.51      0.48       393

    accuracy                           0.78      2000
   macro avg       0.66      0.68      0.67      2000
weighted avg       0.79      0.78      0.79     

In [68]:
sm = SMOTE()
X_train_rs, y_train_rs = sm.fit_resample(X_train, y_train)

In [69]:
for name, model in model_dict.items():
    models = model
    models.fit(X_train_rs, y_train_rs)
    print(f"\n.........{name}........\n")
    y_pred = models.predict(X_test)
    print(f"Accuracy for {name}")
    print(accuracy_score(y_test, y_pred))
    print("\n.......................\n")
    print(f"Confusion matrix for {name}")
    print(confusion_matrix(y_test, y_pred))
    print("\n.......................\n")
    print(f"Classification report for {name}")
    print(classification_report(y_test, y_pred))

    accuracy_per_model[f'accuracy_{name}_model_rs'] = accuracy_score(y_test, y_pred)


.........lr........

Accuracy for lr
0.7245

.......................

Confusion matrix for lr
[[1168  439]
 [ 112  281]]

.......................

Classification report for lr
              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1607
           1       0.39      0.72      0.50       393

    accuracy                           0.72      2000
   macro avg       0.65      0.72      0.66      2000
weighted avg       0.81      0.72      0.75      2000


.........dt........

Accuracy for dt
0.774

.......................

Confusion matrix for dt
[[1323  284]
 [ 168  225]]

.......................

Classification report for dt
              precision    recall  f1-score   support

           0       0.89      0.82      0.85      1607
           1       0.44      0.57      0.50       393

    accuracy                           0.77      2000
   macro avg       0.66      0.70      0.68      2000
weighted avg       0.80      0.77      0.78     

In [70]:
accuracy_per_model

{'accuracy_lr_model': 0.811,
 'accuracy_dt_model': 0.7805,
 'accuracy_rf_model': 0.8635,
 'accuracy_lr_model_rs': 0.7245,
 'accuracy_dt_model_rs': 0.774,
 'accuracy_rf_model_rs': 0.8385}

In [72]:
# performing Hyperameter tuning

from sklearn.model_selection import GridSearchCV

In [80]:
model = RandomForestClassifier()

params = {
    'n_estimators': range(100, 200, 20),
    'criterion': ['gini', 'entropy'],
    'max_depth': range(2, 10),
    'min_samples_split': range(2, 10),
}

In [81]:
grid_search = GridSearchCV(model, param_grid= params, cv = 3, scoring= 'accuracy', n_jobs=-1, verbose= True)

In [82]:
grid_search.fit(X_train_rs, y_train_rs)

Fitting 3 folds for each of 640 candidates, totalling 1920 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 10),
                         'min_samples_split': range(2, 10),
                         'n_estimators': range(100, 200, 20)},
             scoring='accuracy', verbose=True)

In [83]:
grid_search.best_score_

np.float64(0.8470771563827045)

In [84]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 9,
 'min_samples_split': 3,
 'n_estimators': 180}

In [85]:
final_model = grid_search.best_estimator_

In [86]:
final_model

RandomForestClassifier(max_depth=9, min_samples_split=3, n_estimators=180)

In [88]:
y_pred = final_model.predict(X_test)

In [90]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89      1505
           1       0.69      0.55      0.61       495

    accuracy                           0.83      2000
   macro avg       0.78      0.74      0.75      2000
weighted avg       0.82      0.83      0.82      2000



In [91]:
import joblib

In [ ]:
joblib.dump(encoder, 'artifacts/encoder.pkl')
joblib.dump(Scaler, 'artifacts/scaler.pkl')
joblib.dump(final_model, 'artifacts/model.pkl')

['model.pkl']